# Generated by Django 3.0.6 on 2020-06-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppervision', '0002_auto_20200524_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProduct', models.CharField(max_length=255, unique=True)),
                ('statut', models.CharField(blank=True, max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=30)),
                ('date_commande', models.CharField(max_length=255, null=True)),
                ('date_livraison', models.CharField(max_length=255, null=True)),
                ('date_recu', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='code_carte',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
