# Generated by Django 3.0.6 on 2020-06-16 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suppervision', '0003_auto_20200616_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_commande',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_livraison',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_recu',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=255, null=True),
        ),
    ]
