# Generated by Django 3.0.6 on 2020-06-16 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppervision', '0004_auto_20200616_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_commande',
            field=models.DateTimeField(default=datetime.date(2020, 6, 16), max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_livraison',
            field=models.DateTimeField(default=datetime.date(2020, 6, 16), max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_recu',
            field=models.DateTimeField(default=datetime.date(2020, 6, 16), max_length=255),
        ),
    ]
